name: shopapi
favicon: null
layout_spectrum: 0.8184677711687982
typography_spectrum: 0.8636575215496123
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6582628397736698
  lightness: 0.4229789504315704
  saturation: 0.1807257814798504
  rhythmicContrast: 0.5076593731064349
purpose: []
